name: refugee_help_board_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  functional_widget_annotation: ^0.9.2
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  functional_widget: ^0.9.2
  build_runner: ^2.1.9
flutter:
  uses-material-design: true